export { default as Home } from "./home/Home";
export { default as About } from "./about/About";
export { default as NotFound } from "./notFound/NotFound";
export { default as Login } from "./login/Login";
export { default as Signup } from "./signup/Signup";
export { default as Cart } from "./cart/Cart";
export { default as Product } from "./product/Product";
export { default as Checkout } from "./checkout/Checkout";
export { default as AllProducts } from "./allProducts/AllProducts";
